"""
PDF report renderer for librecrawl-technical-seo-audit-mcp (v1.5).

Pipeline:
    existing Markdown report (from server._build_report)
        -> HTML via `markdown` (with tables + fenced code extensions)
        -> CSS template (minimal, neutral branding)
        -> PDF via WeasyPrint (already installed on the VPS)

Branding requirements (NON-NEGOTIABLE):
  - Footer on EVERY page: "Report Generated by LibreCrawl MCP -
    By Aditya Sharma . github.com/adityaarsharma/librecrawl-technical-seo-audit-mcp . Page N of M"
  - Sans-serif body, #2563eb accent on H1/H2 borders only
  - Status colours: green/amber/red for severity
  - No third-party branding anywhere

USAGE:
    from pdf_report import render_pdf
    info = render_pdf(markdown_text, output_path=Path("/tmp/x.pdf"),
                       base_url="https://example.com")
    # -> {"path": "...", "size_bytes": N, "pages": N}
"""

from __future__ import annotations

import html as html_lib
from pathlib import Path
from datetime import datetime


# ── Branding constants ────────────────────────────────────────────────────────

FOOTER_TEXT = (
    "Report Generated by LibreCrawl MCP — By Aditya Sharma · "
    "github.com/adityaarsharma/librecrawl-technical-seo-audit-mcp"
)
ACCENT = "#2563eb"
GREEN  = "#16a34a"
AMBER  = "#eab308"
RED    = "#dc2626"
TEXT   = "#111827"
MUTED  = "#6b7280"
BORDER = "#e5e7eb"

# WeasyPrint can't include unicode em dashes in CSS content strings reliably
# across versions on some servers, so we use a hyphen with hex escapes.
CSS_TEMPLATE = r"""
@page {
    size: A4;
    margin: 22mm 18mm 24mm 18mm;
    @top-left {
        content: "LibreCrawl MCP Audit";
        font-family: -apple-system, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
        font-size: 9pt;
        color: #6b7280;
    }
    @top-right {
        content: string(audit-subject);
        font-family: -apple-system, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
        font-size: 9pt;
        color: #6b7280;
    }
    @bottom-left {
        content: "FOOTER_PLACEHOLDER";
        font-family: -apple-system, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
        font-size: 8pt;
        color: #6b7280;
    }
    @bottom-right {
        content: "Page " counter(page) " of " counter(pages);
        font-family: -apple-system, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
        font-size: 8pt;
        color: #6b7280;
    }
}

@page :first {
    margin: 18mm 18mm 24mm 18mm;
    @top-left { content: ""; }
    @top-right { content: ""; }
}

html { font-size: 10.5pt; }
body {
    font-family: -apple-system, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
    color: TEXT_COLOR;
    line-height: 1.5;
    string-set: audit-subject "";
}

h1 {
    font-size: 22pt;
    color: TEXT_COLOR;
    border-bottom: 2px solid ACCENT_COLOR;
    padding-bottom: 6pt;
    margin-top: 18pt;
    margin-bottom: 14pt;
    string-set: audit-subject content();
}

h2 {
    font-size: 15pt;
    color: TEXT_COLOR;
    border-bottom: 1px solid ACCENT_COLOR;
    padding-bottom: 4pt;
    margin-top: 16pt;
    margin-bottom: 10pt;
    page-break-after: avoid;
}

h3 {
    font-size: 12pt;
    color: TEXT_COLOR;
    margin-top: 12pt;
    margin-bottom: 6pt;
    page-break-after: avoid;
}

h4, h5, h6 {
    color: TEXT_COLOR;
    margin-top: 10pt;
    margin-bottom: 4pt;
    page-break-after: avoid;
}

p { margin: 0 0 8pt 0; }

a { color: ACCENT_COLOR; text-decoration: none; }
a:hover { text-decoration: underline; }

ul, ol { margin: 6pt 0 10pt 18pt; }
li { margin-bottom: 3pt; }

code {
    font-family: "SF Mono", Menlo, Consolas, "Liberation Mono", monospace;
    font-size: 9pt;
    background: #f3f4f6;
    padding: 1pt 4pt;
    border-radius: 3px;
}

pre {
    font-family: "SF Mono", Menlo, Consolas, "Liberation Mono", monospace;
    font-size: 9pt;
    background: #f3f4f6;
    color: TEXT_COLOR;
    padding: 8pt 10pt;
    border-radius: 4px;
    border: 1px solid BORDER_COLOR;
    overflow-x: hidden;
    white-space: pre-wrap;
    word-break: break-all;
    page-break-inside: avoid;
}

blockquote {
    border-left: 3px solid ACCENT_COLOR;
    margin: 10pt 0;
    padding: 4pt 10pt;
    color: MUTED_COLOR;
    background: #f9fafb;
}

hr {
    border: none;
    border-top: 1px solid BORDER_COLOR;
    margin: 14pt 0;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin: 8pt 0 12pt 0;
    font-size: 9pt;
    page-break-inside: auto;
}

table thead {
    display: table-header-group;
}

table tr {
    page-break-inside: avoid;
    page-break-after: auto;
}

table th {
    background: #f3f4f6;
    color: TEXT_COLOR;
    font-weight: 600;
    text-align: left;
    padding: 5pt 7pt;
    border-bottom: 1px solid BORDER_COLOR;
}

table td {
    padding: 5pt 7pt;
    border-bottom: 1px solid BORDER_COLOR;
    vertical-align: top;
    word-break: break-word;
}

table tr:nth-child(even) td { background: #fafafa; }

/* Status colouring - applied via markdown extension or inline spans  */
.sev-green, .pass, .ok { color: GREEN_COLOR; font-weight: 600; }
.sev-amber, .warn       { color: AMBER_COLOR; font-weight: 600; }
.sev-red, .fail, .error { color: RED_COLOR; font-weight: 600; }

/* Cover-page block - first H1 acts as cover title */
.cover {
    padding-top: 30mm;
    page-break-after: always;
}
.cover .subtitle {
    font-size: 12pt;
    color: MUTED_COLOR;
    margin-top: 6pt;
}
.cover .meta {
    font-size: 10pt;
    color: MUTED_COLOR;
    margin-top: 30pt;
}

img { max-width: 100%; height: auto; }
"""

# Apply colour substitutions to CSS template once at module load.
def _build_css() -> str:
    css = CSS_TEMPLATE
    css = css.replace("ACCENT_COLOR", ACCENT)
    css = css.replace("TEXT_COLOR",   TEXT)
    css = css.replace("MUTED_COLOR",  MUTED)
    css = css.replace("BORDER_COLOR", BORDER)
    css = css.replace("GREEN_COLOR",  GREEN)
    css = css.replace("AMBER_COLOR",  AMBER)
    css = css.replace("RED_COLOR",    RED)
    # Footer goes through string substitution (not CSS variable) so it survives
    # WeasyPrint's strict CSS parser. The placeholder includes the unicode
    # bullet (·) directly inside double-quoted content.
    footer_css_safe = (
        FOOTER_TEXT
        .replace("\\", "\\\\")
        .replace('"', '\\"')
    )
    css = css.replace("FOOTER_PLACEHOLDER", footer_css_safe)
    return css


_CSS_CACHE: str | None = None
def _get_css() -> str:
    global _CSS_CACHE
    if _CSS_CACHE is None:
        _CSS_CACHE = _build_css()
    return _CSS_CACHE


# ── HTML rendering ────────────────────────────────────────────────────────────

def _markdown_to_html(md_text: str) -> str:
    """Convert markdown to HTML with table support. Always returns valid HTML."""
    import markdown as md
    return md.markdown(
        md_text,
        extensions=["tables", "fenced_code", "sane_lists", "toc"],
        output_format="html5",
    )


def _wrap_html(body_html: str, title: str) -> str:
    """Wrap rendered HTML in a full document with our CSS embedded."""
    css = _get_css()
    safe_title = html_lib.escape(title)
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{safe_title}</title>
<style>{css}</style>
</head>
<body>
{body_html}
</body>
</html>"""


# ── Public API ────────────────────────────────────────────────────────────────

def render_pdf(markdown_text: str, output_path: Path, base_url: str) -> dict:
    """
    Render a markdown report to PDF with Aditya branding.

    Args:
        markdown_text: Markdown source (from server._build_report).
        output_path:   Where to write the PDF.
        base_url:      Audited URL — used in the page header (string-set on H1).

    Returns:
        {path: str, size_bytes: int, pages: int}

    Raises:
        ImportError if WeasyPrint or markdown is unavailable.
        OSError on filesystem failure.
    """
    # Import inside function so unit tests / dev environments without
    # weasyprint can still import this module.
    from weasyprint import HTML  # type: ignore

    if not markdown_text or not markdown_text.strip():
        raise ValueError("markdown_text is empty - cannot render PDF")

    body_html = _markdown_to_html(markdown_text)
    title = f"LibreCrawl Audit - {base_url}"
    full_html = _wrap_html(body_html, title)

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # WeasyPrint takes a string url-or-content; we use string_io via from_string.
    # base_url passed to HTML lets relative resources resolve (we don't need it,
    # but pass it anyway to avoid warnings).
    document = HTML(string=full_html, base_url=str(output_path.parent)).render()
    pages = len(document.pages)
    document.write_pdf(target=str(output_path))

    size_bytes = output_path.stat().st_size

    return {
        "path":       str(output_path),
        "size_bytes": size_bytes,
        "pages":      pages,
        "generated":  datetime.utcnow().isoformat() + "Z",
    }
