"""v1 technology signatures (correctness > breadth; technology-scoped only)."""

SIGNATURES = {
    "WordPress": {
        "category": "CMS",
        "technology_type": "CMS",
        "signals": [
            {"type": "asset_path", "pattern": r"/wp-content/",
             "strength": "strong"},
            {"type": "asset_path", "pattern": r"/wp-includes/",
             "strength": "strong"},
            {"type": "meta_generator", "pattern": r"WordPress",
             "strength": "strong"},
            {"type": "url_pattern", "pattern": r"/wp-json/",
             "strength": "medium"},
            {"type": "url_pattern", "pattern": r"/wp-admin/",
             "strength": "medium"},
            {"type": "robots_meta", "pattern": r"max-image-preview",
             "strength": "weak"},
        ],
        "negative_signals": [
            {"type": "meta_generator", "pattern": r"Webflow",
             "strength": "strong"},
            {"type": "meta_generator", "pattern": r"Shopify",
             "strength": "strong"},
        ],
        "version_extractor": {
            "type": "regex",
            "pattern": r"WordPress ([\d.]+)",
        },
        "applicability_requirement": "STRONG_2",
        "notes": "drives CMS rule applicability only at High/STRONG_2",
    },
    "WooCommerce": {
        "category": "Ecommerce",
        "technology_type": "Ecommerce",
        "signals": [
            {"type": "meta_generator", "pattern": r"WooCommerce",
             "strength": "strong"},
            {"type": "asset_path",
             "pattern": r"/wp-content/plugins/woocommerce/",
             "strength": "strong"},
            {"type": "url_pattern", "pattern": r"/product/",
             "strength": "medium"},
            {"type": "url_pattern", "pattern": r"/shop/",
             "strength": "weak"},
        ],
        "version_extractor": {"type": "regex", "pattern": r"WooCommerce ([\d.]+)"},
    },
    "Shopify": {
        "category": "CMS",
        "technology_type": "Ecommerce",
        "signals": [
            {"type": "meta_generator", "pattern": r"Shopify",
             "strength": "strong"},
            {"type": "asset_path", "pattern": r"cdn\.shopify\.com",
             "strength": "strong"},
            {"type": "response_header", "pattern": r"x-shopid",
             "strength": "medium"},
            {"type": "url_pattern", "pattern": r"/products/",
             "strength": "weak"},
            {"type": "url_pattern", "pattern": r"/collections/",
             "strength": "weak"},
        ],
    },
    "Webflow": {
        "category": "CMS",
        "technology_type": "CMS",
        "signals": [
            {"type": "meta_generator", "pattern": r"Webflow",
             "strength": "strong"},
            {"type": "response_header", "pattern": r"^webflow",
             "strength": "medium"},
            {"type": "script_src", "pattern": r"/assets/.*\.js",
             "strength": "weak"},
        ],
    },
    "Avada": {
        "category": "Theme",
        "technology_type": "Theme",
        "signals": [
            {"type": "asset_path", "pattern": r"/wp-content/themes/Avada/",
             "strength": "strong"},
            {"type": "meta_generator", "pattern": r"Avada",
             "strength": "medium"},
        ],
    },
    "Astra": {
        "category": "Theme",
        "technology_type": "Theme",
        "signals": [
            {"type": "asset_path", "pattern": r"/wp-content/themes/astra/",
             "strength": "strong"},
            {"type": "meta_generator", "pattern": r"Astra",
             "strength": "medium"},
        ],
    },
    "Elementor": {
        "category": "Page Builder",
        "technology_type": "Page Builder",
        "signals": [
            {"type": "asset_path",
             "pattern": r"/wp-content/plugins/elementor/",
             "strength": "strong"},
            {"type": "script_src", "pattern": r"/elementor/",
             "strength": "medium"},
            {"type": "meta_generator", "pattern": r"Elementor",
             "strength": "medium"},
        ],
    },
    "Yoast SEO": {
        "category": "SEO Technology",
        "technology_type": "SEO Plugin",
        "signals": [
            {"type": "meta_generator", "pattern": r"Yoast SEO",
             "strength": "strong"},
            {"type": "asset_path",
             "pattern": r"/wp-content/plugins/yoast-seo/",
             "strength": "strong"},
            {"type": "robots_meta",
             "pattern": r"max-image-preview:large",
             "strength": "weak"},
        ],
    },
    "Rank Math": {
        "category": "SEO Technology",
        "technology_type": "SEO Plugin",
        "signals": [
            {"type": "meta_generator", "pattern": r"Rank Math",
             "strength": "strong"},
            {"type": "asset_path",
             "pattern": r"/wp-content/plugins/seo-by-rank-math/",
             "strength": "strong"},
        ],
    },
    "GA4": {
        "category": "Analytics",
        "technology_type": "Analytics",
        "signals": [
            {"type": "analytics_fingerprint", "pattern": r"ga4_id",
             "strength": "strong"},
            {"type": "script_src", "pattern": r"/gtag/js\?id=G-",
             "strength": "strong"},
        ],
    },
    "GTM": {
        "category": "Tag Manager",
        "technology_type": "Tag Manager",
        "signals": [
            {"type": "analytics_fingerprint", "pattern": r"gtm_id",
             "strength": "strong"},
            {"type": "script_src", "pattern": r"/gtm\.js\?id=",
             "strength": "strong"},
        ],
    },
    "Meta Pixel": {
        "category": "Advertising Pixel",
        "technology_type": "Pixel",
        "signals": [
            {"type": "analytics_fingerprint", "pattern": r"fb_pixel",
             "strength": "strong"},
            {"type": "script_src", "pattern": r"/tr\?id=",
             "strength": "strong"},
        ],
    },
    "Cloudflare": {
        "category": "CDN",
        "technology_type": "Edge/CDN",
        "signals": [
            {"type": "response_header", "pattern": r"^cf-ray$",
             "strength": "strong"},
            {"type": "response_header", "pattern": r"^cf-cache-status$",
             "strength": "strong"},
            {"type": "response_header", "pattern": r"^server$.*cloudflare",
             "strength": "medium"},
        ],
    },
    "nginx": {
        "category": "Web Server",
        "technology_type": "Web Server",
        "signals": [
            {"type": "response_header", "pattern": r"^server$.*nginx",
             "strength": "strong"},
            {"type": "response_header", "pattern": r"^server$.*openresty",
             "strength": "medium"},
        ],
    },
    "Apache": {
        "category": "Web Server",
        "technology_type": "Web Server",
        "signals": [
            {"type": "response_header", "pattern": r"^server$.*apache",
             "strength": "strong"},
        ],
    },
    "LiteSpeed": {
        "category": "Web Server",
        "technology_type": "Web Server",
        "signals": [
            {"type": "response_header", "pattern": r"^server$.*litespeed",
             "strength": "strong"},
            {"type": "response_header", "pattern": r"^x-litespeed-cache$",
             "strength": "strong"},
        ],
    },
    "jQuery": {
        "category": "JavaScript Library",
        "technology_type": "JS Library",
        "signals": [
            {"type": "script_src", "pattern": r"jquery(?:\.min)?\.js",
             "strength": "strong"},
            {"type": "asset_path", "pattern": r"/wp-includes/js/jquery",
             "strength": "strong"},
        ],
    },
}
